### PR TITLE
Added estimation of time left for future_map functions

### PR DESCRIPTION
**Pull request by cipherz**
Crude estimation of time left for future_map functions.

### CODE REVIEW

**Comment by cipherz** [comment]
My apologies, forgot to divide the estimated time left by the number of workers currently active.

**Comment by DavisVaughan** [comment]
I like this idea and I'll get to looking at it eventually, but it may take a few days. Thanks for the initial work!

**Comment by cipherz** [comment]
Thanks and no problem!

**Comment by mike-lawrence** [comment]
Bumping this PR as it seems to be ready but it's been a year since submission.

**Comment by DavisVaughan** [comment]
I appreciate the PR! But now that progressr is being worked on as part of an "official" solution, I'm going to wait on it rather than adding partial solutions (like my own progress bar) to furrr.
https://github.com/HenrikBengtsson/progressr

**Pull request closed without merging**
